### ISSUE TITLE
Problems using copyFieldGroup for customized OOTB fieldgroups

### ISSUE THREAD

**Issue by mdonke** [adobe/aepp#28]
### Expected Behaviour
I can copy all fieldgroups.

### Actual Behaviour
Copy of fieldgroups fails for customized out-of-the-box fieldgroups.

#### Steps to Reproduce

1. create a profile schema
2. add "consent and preferences" fieldgroup
3. add a field to this fieldgroup (customize it)
4. try to execute code below

#### Platform and Version
latest aepp, Linux

#### Sample Code that illustrates the problem
```
import aepp
from aepp import schema
original_config = aepp.importConfigFile(path="credentials.json", connectInstance=True)
original_instance = schema.Schema(config=original_config)
fg_original = original_instance.getFieldGroup("_my.mixins.7dc518b25875a5562fd9aad33ca2fa0fd951c08c95faebd1")
fg_copy = original_instance.copyFieldGroup(fg_original, title="new", tenantId="_other")
```
#### Logs taken while reproducing problem
```
Traceback (most recent call last):
  File "/home/xxx/work/aepdeploy/xxx/../bug.py", line 9, in <module>
    fg_copy = original_instance.copyFieldGroup(fg_original, title="new", tenantId="other")
  File "/home/xxx/.local/lib/python3.9/site-packages/aepp/schema.py", line 1219, in copyFieldGroup
    obj["definitions"]["property"]["properties"][tenantId] = obj["definitions"]["property"]["properties"][oldTenant]
KeyError: '_my'
```

This is how the fieldgroup looks in the UI:
![Screenshot 2024-01-02 141855](https://github.com/adobe/aepp/assets/60607190/b371313b-eda1-4968-aa8c-32c922101339)

**Comment by magcode** [comment]
I made an attempt to fix the issue.

In my code above to reproduce there was a bug.
One needs to include `full=false`.

``` 
...
fg_original = original_instance.getFieldGroup("_my.mixins.7dc518b25875a5562fd9aad33ca2fa0fd951c08c95faebd1", full=False)
...
```

However, still changes to `schema.py` are needed I think.

**Comment by mdonke** [comment]
I made an attempt to fix the issue.

In my code above to reproduce there was a bug.
One needs to include `full=False`:

```
...
fg_original = original_instance.getFieldGroup("_my.mixins.7dc518b25875a5562fd9aad33ca2fa0fd951c08c95faebd1", full=False)
...
```

However, still changes to `schema.py` are needed I think.

**Comment by pitchmuc** [comment]
Hello @mdonke 

Thanks or raising this. 
Custom OOTB fieldgroups are quite hard to deal with. 
I will see if I can find a way to apply that change but I would imagine it requires a special operation to clone this OOTB in the new sandbox / org. 

I am not sure I would be able to support it to be honest. 

For some other capability of Schema and Schema Manager, Field Group Manager, I am simply not supporting these OOTB field groups (for write operation), only supports reads.

**Comment by mdonke** [comment]
Hello Julien,

we are currently testing my fix with the goal of cloning the modified OOTB fieldgroups to another sandbox/org.
Will let you know how it went asap.

**Comment by pitchmuc** [comment]
hey @mdonke 
Did it work ?

**Comment by mdonke** [comment]
I'm still waiting for confirmation about the "different org" case.
I can confirm its working when creating such a modified OOTB fieldgroup in another sandbox in the same org.

**Comment by pitchmuc** [comment]
I looked at the solution you provided, I think it is because the `full=false` will not return the custom part, so you can just return the default OOTB. 
I am not sure. 
In any case, OOTB field group should be found in any other sandbox with different ID anyway. 

I am really curious to see what you did.

**Comment by mdonke** [comment]
Have you seen the [commit](https://github.com/mdonke/aepp/commit/6bfddedf9e0e7c2f595938140696101e88e77595)? 
(Ignore the dateTime change, that was an accident)

Its hard to explain looking at code only. One needs to see the current json structure in every step to understand the loops. lookups and manipulation.

I just gave it a try with a modified tenant id (for cross orgid scenarious): Its working fine, I get a warning (?) though:

"The schema's meta:immutableTags array could not be found. Once this field is added to a schema, it cannot be removed."

We will actively use/test this code in the upcoming months. If you don't feel safe merging it yet, I'll keep it in my repo for now.

**Comment by pitchmuc** [comment]
Because it is never too late, I will copy your code and merge it in the next release
